### ISSUE TITLE
trying to make it works with GBDK

### ISSUE THREAD

**Issue by skarab** [Pegmode/Deflemask-GB-Engine#10]
Hello,
I'm trying to make it works with GBDK, its not the same assembler, can't declare variables and I dont know how to handle this line :
ld hl,VgmLookupPointer ;load data pointer

by making C globals i can bind high/low 8bits, but what i need to do here ?
please help.

here is non working code:
`;SoundStatus:         ds 1;play,stop,pause state
;CurrentSoundBank:  
;CurrentSoundBankI:ds 1;current song data bank
;CurrentSoundBankD: ds 1;current song data bank
;VgmLookupPointer:    ;current frame pointer
;VgmLookupPointerI:ds 1
;VgmLookupPointerD: ds 1
;SoundWaitFrames:     ds 1;number of frames to currently wait

_DMEngineInit::
    ld a,#1
    ld (CurrentSoundBankD),a
    ld a,#0x40;load 0x4000 in pointer
    ld (VgmLookupPointerI),a

    ld a,#1
    ld (SoundWaitFrames),a;set to not waiting any frames
    xor a
    ld (SoundStatus),a;set engine to not playing status
    ld (VgmLookupPointerD),a
    ld (CurrentSoundBankI),a
    ret

_DMEngineUpdate::
checkEngineStatus: ;check if the engine is currently playing a song
    ld a,(SoundStatus)
    cp #1
    jr z,checkIsWaitFrame
    ret
checkIsWaitFrame: ;check if the engine is currently in a wait state
    ld a,(SoundWaitFrames)
    cp #1
    jr z,loadCurrentBank
    dec a
    ld (SoundWaitFrames),a
    ret
loadCurrentBank:
    ld a,(CurrentSoundBankI)
    ld b,a
    ld a,(CurrentSoundBankD)
    ld (#0x2000),a ;rROMB0
    ld a,b
    ld (#0x3000),a ;rROMB1
    
commandCheckInit:
    ld hl,VgmLookupPointer;load data pointer
	ld b,(hl)
    inc hl
    ld c,(hl)
    ld h,b
    ld l,c
commandCheck:
    ld a,(hl) ;load data at data pointer, dont inc hl here because it may not be needed for current command
checkWriteCmd:
    bit 7,a
    jr z,checkWaitCmd
    inc hl
    ld a, (hl+)
    ld b, #0xFF
    ld c, a
    ld a, (hl+)
    ld (bc), a
    jr commandCheck
checkWaitCmd:
    bit 6,a
    jr z,checkNextBank
    inc hl
    ld a,(hl+)
    ld (SoundWaitFrames),a
    jr endFrame
checkNextBank:
    bit 5,a
    jr z,checkLoop
    ld bc, #0x4000
    ld hl,VgmLookupPointer ;load data pointer
	ld (hl), b
    inc hl
    ld (hl), c
    ld a,(CurrentSoundBankI)
    ld b,a
    ld a,(CurrentSoundBankD)
    ld c, a
    inc bc
    ld a, b
    ld (CurrentSoundBankI),a
    ld a, c
    ld (CurrentSoundBankD),a
    ret ;DO NOT END FRAME NORMALLY
checkLoop: ;unimplemented
;    bit 4,a
;    jr z,checkEndSong
;    ;load new bank
;    ld hl, loopBank
;    ld a, (hl+)
;    ld (CurrentSoundBankD),a
;    ld a, (hl)
;    ld (CurrentSoundBankI),a
;    ;load new Address
;    ld hl, loopAddress
;    ld a, (hl+)
;    ld (VgmLookupPointerD),a
;    ld a, (hl)
;    ld (VgmLookupPointerI),a
    ret
checkEndSong:
    bit 3,a
    jr z,errorInCheck
    ;No need to set up registers for quiet status. should be done in tracker via envelopes, OFF or ECxx
    xor a
    ld (SoundStatus),a
    call resetSound
    jr endFrame
errorInCheck:
    ;handle stuff
    ld b,b;debug breakpoint
endFrame:
    ld a, h
    ld (VgmLookupPointerI),a
    ld a, l
    ld (VgmLookupPointerD),a
    ret

resetSound:
    xor a
    ldh (#0x10), a
    ldh (#0x12), a
    ldh (#0x17), a
    ldh (#0x22), a
    ldh (#0x11), a
    ldh (#0x11), a
    ldh (#0x16), a
    ldh (#0x1A), a
    ldh (#0x21), a
    ld a, #0x8f
    ldh (#0x26), a
    ld a, #0xFF
    ldh (#0x25), a
    ld a, #0x77
    ldh (#0x24), a
    ld a, #0x20
    ldh (#0x1C), a
    ld a, #0xF7
    ldh (#0x21), a
    ret`

**Comment by Pegmode** [comment]
Those addresses are WRAM addresses. Some of them contain the high and low bytes of a 16-bit address. If your assembler does not support allocating addresses automatically or labels (which I assume you're calling "variables") change all the labels for corresponding memory addresses. For example you could replace `VgmLookupPointerI` with the value `0xC1`. 
[RGBDS documentation for memory address alloc ](https://rgbds.gbdev.io/docs/v0.5.1/rgbasm.5#Declaring_variables_in_a_RAM_section)

I don't use GBDK but since it's C I'm assuming you can just define those labels as pointers? Why not manually set them to addresses inside WRAM? If you're not familiar with ASM I can see that you might get confused with pointers having the same value. Eg in the code you posted `VgmLookupPointer:` and `VgmLookupPointerI:` contain the same address.

I'm not entirely sure of exactly what you are asking but I hope that answers your question, if not please feel free to reply.

**Comment by Pegmode** [comment]
Just to be clear, the labels are all 16-bit addresses in WRAM but the values they contain are 8-bit

**Comment by skarab** [comment]
oh ok, I thought VgmLookupPointer was 16 bit value, with VgmLookupPointeI
pointing to high 8bit and  VgmLookupPointerD pointing at low 8bit ?

Le ven. 2 juil. 2021 à 16:37, Daniel Chu ***@***.***> a
écrit :

**Comment by skarab** [comment]
this is why i dont know how to bind from C,

i can declare unsigned char VgmLookupPointerI, then it'll be auto binded in
the global asm

Le ven. 2 juil. 2021 à 17:53, Alexandre Chambriat ***@***.***> a
écrit :

**Comment by skarab** [comment]
Thanks for your answer, i'll need to do some tryings!

Le ven. 2 juil. 2021 à 17:54, Alexandre Chambriat ***@***.***> a
écrit :

**Comment by Pegmode** [comment]
No worries. Glad I could help.

**Comment by skarab** [comment]
awesome, managed to make it works! thanks!

but I've hardcoded the addresses :

;SoundStatus 0xCC00 0xCC00 ;play,stop,pause state
;CurrentSoundBank   ;current song data bank
;CurrentSoundBankHigh 0xCC02  0xCC02
;CurrentSoundBankLow 0xCC03  0xCC03
;VgmLookupPointer 0xCC04 0xCC04 ;current frame pointer
;VgmLookupPointerHigh 0xCC04  0xCC04
;VgmLookupPointerLow 0xCC05  0xCC05
;SoundWaitFrames 0xCC06 0xCC06 ;number of frames to currently wait

I failed to pass it from C side because this asm doesnt want ld hl,#0xCC04
from "variable".

Regards.

Le sam. 3 juil. 2021 à 05:47, Daniel Chu ***@***.***> a
écrit :

**Comment by skarab** [comment]
Oh between.. making Rebels demo :
https://youtu.be/I-hLTaJKth8
(private) you'll be credited :)
Cheers!

Le sam. 3 juil. 2021 à 17:31, Alexandre Chambriat ***@***.***> a
écrit :

**Comment by skarab** [comment]
between, the song is to much fast, musician has to check option somewhere,
I've modified your code by :
if(ENGINE_RATE != 50){
                            static int alreadyWarned = 0;
                            if (alreadyWarned == 0)
                            {
                                printfLibless("Warning: PAL wait tick found
in non PAL timed module! Did you enter the correct engine speed?\n");
                                alreadyWarned = 1;
                            }
                            //exit(1);
                        }

so it just warn and export even if not correct.

Le sam. 3 juil. 2021 à 19:42, Alexandre Chambriat ***@***.***> a
écrit :
