### ISSUE TITLE
silly warning related to fread

### ISSUE THREAD

**Issue by franciscod** [Pegmode/Deflemask-GB-Engine#11]
/home/defle/deflemask/src/rombuilders/gbvgm/gbvgm.c:108:5: warning: ignoring return value of 'fread', declared with attribute warn_unused_result [-Wunused-result]
     fread(vgmBuffer->buffer,1,fileSize,f);

**Comment by Pegmode** [comment]
I'll fix this in the next update

**Comment by Pegmode** [comment]
Patched in https://github.com/Pegmode/-DeflemaskGBVGM-/commit/bcb44c944dc492c0315a9d06fb7f20dd883f7c9f

**Comment by Pegmode** [comment]
new update pushed
